### ISSUE TITLE
Most  of the methods to scrap the metrics aren't working

### ISSUE THREAD

**Issue by erickhun** [BigIntJin/google-local-guides-api#4]
Those methods below aren't working. I guess it was when @JinKim7  released the library , but Google Maps updated their UI what broke the code

```js
          reviews: this.getReviews(),
          ratings: this.getRatings(),
           questions: this.getQuestions(),
           placesAdded: this.getPlacesAdded(),
           edits: this.getEdits(),
           facts: this.getFacts(),
           videos: this.getVideos(),
           qa: this.getQA(),
           roadsAdded: this.getRoadsAdded(),
           listsPublished: this.getPublishedLists()
```

Those ones still works : 
```js
            points: this.getPoints(),
            level: this.getLevel(),
```

I guess we would need to simulate how to get the pop-up with all those informations to make it work again

**Comment by fosfomycin** [comment]
@erickhun i tried running it and it seems to still work. 
Try running this in a new npm project
```
npm init -y
```

install `google-local-guides-api` package
```
npm i google-local-guides-api
```

make a new `index.js` file and put this code in there:
```javascript
const ContributionMetadata = require('google-local-guides-api');

let contributionMetadata = new ContributionMetadata();

// This initializes your link into the response body -- has to be in async/await func
run = async () => {
    await contributionMetadata.init("https://www.google.com/maps/contrib/[ID]");

    // You can call get specific attributes like points
    let points = contributionMetadata.getPoints();

    // ...Or use getMetadata() to get all available attributes from you profile
    let metadata = await contributionMetadata.getMetadata();

    console.log('metadata: ', metadata);
}

run().then();
```

but replace the `[ID]` param with your own ID from when you're redirected to your own profile when clicking on this link -- https://www.google.com/maps/contrib/

then run the `index.js` file.

![image](https://user-images.githubusercontent.com/6789394/94370670-275e6180-00a6-11eb-922c-33e51f9558e1.png)


Let me know if that works or not.

**Comment by andaryjo** [comment]
I can confirm that all methods still work. However, there are a few things I noted:
- Parsing only works when the language of the site is english. So you would need to make sure that you append `?hl=en` as query parameter to the URL in case english is not your default language (not sure how Google determines that).
- Method `getPublishedLists()` breaks in case there is only 1 published list. Because in that case the wording in the source code changes from `x published lists` to `1 published list`. The method would then throw an error because no match was found, so some error handling would be required for that.
```
(node:10440) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at ContributionMetadata.getMatch (/home/x/Projects/lgtest/node_modules/google-local-guides-api/src/ContributionMetadata.js:159:24)
    at ContributionMetadata.getPublishedLists (/home/x/Projects/lgtest/node_modules/google-local-guides-api/src/ContributionMetadata.js:125:21)

```
